jobserver:
    type:     jenkins
    url:      http://localhost:8080
    username:
    password:

    joblist:
        -
          label:    job0
          path:
          display:  true

        -
          label:    job1
          path:
          display:  true

        -
          label:    job2
          path:
          display:  true

